import { getInjectedPiPhiWidgetHost } from "piphi-network-widget-sdk";
import { formatEventTime, groupEvents, lifecycleMessage, normalizeEvents, normalizeStatus } from "./view-model.js";
const host=getInjectedPiPhiWidgetHost(),root=document.querySelector("#piphi-widget-root")||document.body;
const [context,settings,defaultTitle,waiting,empty,allDay]=await Promise.all([host.getContext(),host.getSettings(),host.translate("widget.title"),host.translate("widget.waiting"),host.translate("widget.empty"),host.translate("widget.all_day")]);
const locale=context.localization?.locale||"en";let currentStatus="loading",events=[];
root.innerHTML=`<style>:root{color-scheme:light dark;font:14px/1.4 system-ui,sans-serif}*{box-sizing:border-box}main{min-height:220px;padding:18px;color:CanvasText;background:Canvas;border-radius:18px}header{display:flex;align-items:center;justify-content:space-between;gap:12px}h2{margin:0;font-size:1.05rem}.count{font-variant-numeric:tabular-nums;opacity:.65}.days{display:grid;gap:14px;margin-top:18px}.day h3{position:sticky;top:0;margin:0;padding:6px 0;background:Canvas;font-size:.82rem;text-transform:uppercase}.events{display:grid;gap:8px}.event{display:grid;grid-template-columns:minmax(82px,.35fr) 1fr;gap:12px;padding:12px;border:1px solid color-mix(in srgb,CanvasText 14%,transparent);border-inline-start:4px solid #6d5bd0;border-radius:12px}.event:focus-visible{outline:3px solid #725be8;outline-offset:2px}.time{font-variant-numeric:tabular-nums;font-weight:650}.title{font-weight:700}.meta,[role=status]{opacity:.68}.compact .event{padding:8px}.empty{padding:32px 12px;text-align:center;opacity:.7}@media(max-width:420px){main{padding:14px}.event{grid-template-columns:1fr;gap:4px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}</style><main dir="${esc(context.localization?.direction||"ltr")}" class="${settings.compact?"compact":""}"><header><h2>${esc(String(settings.title||defaultTitle))}</h2><span class="count" aria-live="polite">0</span></header><div class="days"></div><p role="status">${esc(waiting)}</p></main>`;
const daysNode=root.querySelector(".days"),statusNode=root.querySelector("[role=status]"),countNode=root.querySelector(".count");
const stop=await host.subscribeState({capabilityIds:["calendar_events","calendar_active","calendar_name","timezone","last_updated_at"]},event=>{currentStatus=normalizeStatus(event.status||event.kind);let timezone;if(event.kind==="snapshot"||event.kind==="point"){const state=event.data?.primaryState||event.data?.state||event.data?.value||event.data||{};events=normalizeEvents(state.calendar_events,{days:settings.days});timezone=state.timezone;}render(timezone);});
window.addEventListener("pagehide",stop,{once:true});await host.ready({height:420});
function render(timezone){countNode.textContent=String(events.length);statusNode.textContent=lifecycleMessage(currentStatus,events.length,{waiting,empty});if(!events.length){daysNode.innerHTML=`<div class="empty">${esc(lifecycleMessage(currentStatus,0,{waiting,empty}))}</div>`;return;}daysNode.innerHTML=groupEvents(events,locale,timezone).map(group=>`<section class="day"><h3>${esc(group.label)}</h3><div class="events">${group.events.map(event=>`<article class="event" tabindex="0" aria-label="${esc(event.title)}"><div class="time">${esc(formatEventTime(event,locale,timezone,allDay))}</div><div><div class="title">${esc(event.title)}</div><div class="meta">${esc([event.calendar,settings.show_location!==false&&event.location].filter(Boolean).join(" · "))}</div></div></article>`).join("")}</div></section>`).join("");}
function esc(value){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);}
